name: PR Lint

on:
  pull_request:
    branches:
      - main # Or your branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint commits
        run: npx commitlint --from=$GITHUB_BASE_REF --to=$GITHUB_HEAD_REF
